### PR TITLE
Make everything use radians

### LINKED ISSUE #31: Inconsistent use of radians vs. degrees
The trigonometric functions in Handmade Math use radians for angles. `HMM_Perspective`, on the other hand, uses degrees.

We should make this usage consistent between the two, or find a way to clarify which uses radians and which uses degrees.

### PR DESCRIPTION
**Pull request by bvisness**
Resolves #31. 

**TODO:**
- [x] Add documentation

### CODE REVIEW

**Comment by bvisness** [comment]
@StrangeZak What should the trig functions like `HMM_SinF` do when `HANDMADE_MATH_USE_DEGREES` is defined? It feels dirty to me to make trig functions take degrees, but I think it would make sense and be the most consistent.

**Comment by bvisness** [comment]
Actually, that gets thorny because of how the trig functions are used internally. Should we consider making trig functions "private" in the same way we were considering for HMM_LinearCombineSSE? (#109)

**Comment by RandyGaul** [comment]
For my use cases I would prefer all functions to use one or other between degrees and radians, with no macros to change behavior whatsoever. Macros that opaquely change behavior internally are too complicated compared to their utility value. And instead provide a degree to radians and a radians to degree macro pair, and let the user handle it however they like from there.

**Comment by bvisness** [comment]
The intent is for all functions to use radians, and I'm adding an HMM_ToDegrees function/macro to complete the pair. I would still like to provide a flag to use degrees, but I think to make that happen, we will need to hide our trig functions.

It may be, though, that with the trig functions gone, there just aren't enough uses of angles to justify the existence of Degree Mode.

**Comment by StrangeZak** [comment]
@bvisness Is there anything i can do to work towards closing this PR

**Comment by bvisness** [comment]
Hmm, I really don't remember where I left this. Clearly I added a conversion macro and some tests. But coming at it again with fresh eyes, I really don't think it's worth the effort, and I think we should just stick with radians everywhere, the end.

So I guess this branch should be updated to do that?

**Comment by StrangeZak** [comment]
Yep agreed. Everything should be radians.

**Comment by StrangeZak** [comment]
Id like to get this closed if you can allocate some time towards it :D

**Comment by bvisness** [comment]
I think this is good to go.

**Comment by StrangeZak** [comment]
Wooo. Ill give it a review now. This is awesome

**Comment by bvisness** [comment]
Travis isn't working, so I'm trying to sort that out. But the tests are ok locally; hopefully they are for you too.

**Comment by bvisness** [comment]
Travis had an outage, and they're slowly recovering, but it seems that everything is passing.

**Comment by bvisness** [comment]
@StrangeZak Can you look at this, #113, and #114 when you have a chance?

**Comment by StrangeZak** [comment]
happy to see this done feel free to merge it

**Pull request merged**
