### PR TITLE
Add test coverage macros

### PR DESCRIPTION
**Pull request by bvisness**
This exhausting PR adds test coverage macros, and fixes the issues that arose from them.

### CODE REVIEW

**Comment by RandyGaul** [comment]
Here's a function your test can run to turn on red/green colors when run under Windows.

```cpp
// At the time of writing, this define requires fairly recent windows version, so it's
// safest to just define it ourselves... Should be harmless!
#ifndef ENABLE_VIRTUAL_TERMINAL_PROCESSING
#	define ENABLE_VIRTUAL_TERMINAL_PROCESSING 0x0004
#endif

// https://docs.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences
void windows_turn_on_console_color()
{
	HANDLE h = GetStdHandle(STD_OUTPUT_HANDLE);
	DWORD flags = 0;
	GetConsoleMode(h, &flags);
	flags |= ENABLE_VIRTUAL_TERMINAL_PROCESSING;
	SetConsoleMode(h, flags);
}
#endif
```

**Comment by bvisness** [comment]
Ah nice, I'll give that a try once I'm at my PC. I haven't yet tried to get these tests running on Windows since they're dependent on make, and actually I think on GCC/Clang (for the C part of [this weird initializer thing](https://github.com/HandmadeMath/Handmade-Math/blob/master/test/initializer.h))

**Comment by RandyGaul** [comment]
Wait really? Where is the make dependency? Can this be removed? That seems like an annoying dependency for Windows users that should probably be avoided.

**Comment by bvisness** [comment]
I guess there's technically no make dependency if you just want to run the tests locally. But I do have a makefile set up for running everything, which is what I use on my Mac and in Travis. Sorry for using the wrong terminology.

Assuming MSVC can do a similar initialization thing in C, this all should be able to work on Windows. And if that doesn't work, I bet at least the C++ tests will work.

**Comment by StrangeZak** [comment]
At work tomorrow ill make a build script so we can try to build and run the tests on windows. This will just be a batch file to make things easy for us. I can add a VS sln in the future if needed, but those aren't very version independent

**Comment by bvisness** [comment]
@StrangeZak I beefed up issue #92 to track testing on Windows.

**Pull request merged**
