### PR TITLE
Fixed issue related to unsigned/signed-ness of HMM_Power

### PR DESCRIPTION
**Pull request by StrangeZak**
Fixes warning on GCC when compiling with -Weverything

`./HandmadeMath.h:2178:37: warning: operand of ? changes signedness: 'int' to 'unsigned int' [-Wsign-conversion]
    unsigned int X = Exponent < 0 ? -Exponent : Exponent;
                 ~                  ^~~~~~~~~
./HandmadeMath.h:2178:49: warning: operand of ? changes signedness: 'int' to 'unsigned int' [-Wsign-conversion]
    unsigned int X = Exponent < 0 ? -Exponent : Exponent;
                 ~                              ^~~~~~~~
`

Had an issue with unsigned/signed. We were using a regular "int" as the parameter. Making it unsigned would make no sense due to the comparison

This CL simply removes the "unsigned" from the variable X to prevent the warning from generating again.

### CODE REVIEW

**Comment by StrangeZak** [comment]
Both of these CLs fix warnings generated by GCC with the -Weverything flag. One more change needs to be done to cleanly compile on GCC with -Weverything but that is currently being sorted with issue #99

**Comment by StrangeZak** [comment]
Also specifically less than 4.8 we will only disable this warning check out this thread https://gcc.gnu.org/bugzilla/show_bug.cgi?id=25137

**Comment by StrangeZak** [comment]
@bvisness Is this good to merge? Pinged you as a reviewer a few days ago

**Comment by bvisness** [comment]
I'm a little concerned that our tests were passing with it in this state...I think I'll look at a couple of those cases and then this is good to go.

**Comment by bvisness** [comment]
Oh never mind, I see what the issue was. This is good to go.

**Pull request merged**
