### PR TITLE
Run tests on Linux, macOS, and Windows

### LINKED ISSUE #92: No way to run tests on Windows
Wondering if there's any interest in making project files (or some other build solution?) for running the test suite in MSVC.

I am happy to put them together if they'd be useful. I have VS 2015 and got those projects working there. Not sure if VS 2017 requires a separate solution version, but I could also make that project if it does.

I cannot get VS 2012 working without modifying the tests. C99 designated initializers weren't supported until VS 2013, it seems, and the tests use those. I could convert the tests to not use that feature (if the lib itself doesn't use it). I wanted to gauge interest in all this before starting that.

### PR DESCRIPTION
**Pull request by bvisness**
Resolves #92.

### CODE REVIEW

**Comment by bvisness** [comment]
@StrangeZak Wanna check this out and try running `test.bat`?

**Comment by StrangeZak** [comment]
Sure

**Comment by StrangeZak** [comment]
test.bat compiles everything okay

**Comment by bvisness** [comment]
Ok great, then you can try running:
```
build\hmm_test_c
build\hmm_test_c_no_sse
build\hmm_test_cpp
build\hmm_test_cpp_no_sse
```

**Comment by bvisness** [comment]
I guess I'll just update the batch script to run those as they compile. That's how the other one works now anyway.

**Comment by bvisness** [comment]
Since it seems to compile for you, and the tests are passing in Travis, I'm gonna go ahead and merge this. You should be able to run `test.bat` whenever you want now!

**Pull request merged**
